#include <QTextStream>

int  main (void) {
	QTextStream out(stdout);

	QString str1 = "This is the normal way of initiating a string";
	out << str1 << endl;

	QString str2("This is an object oriented way of initiating a string");
	out << str2 << endl;

	std::string s1 = "This is a C++ standard string assigned to a QString";
	QString str3 = s1.c_str();
	out << str3 << endl;

	std::string s2 = "this is a string generated by extracting the data from a C++ standard string";
	QString str4 = QString::fromLatin1(s2.data(), s2.size());
	out << str4 << endl;

	char s3[] = "This is a C String or Character array stored as a QString";
	QString str5(s3);
	out << str5 << endl;

}
